#ALIASES $HOME/.bash_aliases

##GIT
alias gs='git status'
alias gcm='git commit --no-verify -am'
alias gps='git push --no-verify'
alias gpsf='git push origin --no-verify --force'
alias gpl='git pull'
alias gl='git log --oneline --decorate --graph'
alias gt='git tag'
alias gtps='git push origin --no-verify --tags'
alias gb='git branch'
alias gc='git checkout'
alias gcp='git cherry-pick'
alias gm='git merge'
alias gd='git diff'
alias grsh='git reset --hard'
alias grp='git remote prune origin'
alias gru='git remote get-url origin'

##DOCKER
alias dup='docker-compose up'
alias dlog='docker-compose logs -f'
alias dtail='docker-compose logs -f --tail 20'
alias dexec='docker-compose exec'
alias dstop='docker ps -q | xargs docker stop'
alias drst='docker-compose restart'
alias ddown='docker-compose down'
alias dps='watch docker-compose ps'
alias dinsp='docker inspect -f "{{.Name}} - {{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}" $(docker ps -aq)'
alias dimgs='docker images -a'
alias drmAll='docker system prune --volumes -f && docker image prune -a -f'
alias dsys='tmux new "docker stats --all" ";" split -p 50 "watch docker ps -a"'

##tmux
alias tm='tmux new-session "bash -i"'
alias tmat='tmux at'
alias tml='tmux list-sessions'
alias tmatt='tmux attach-session -t'
alias tmk='tmux kill-session -t'

##SYS
alias upd='sudo sh -c "apt update && apt upgrade -y && apt dist-upgrade -y && snap refresh && apt autoremove -y && apt autoclean && apt clean"'
